import type { ApiEndpointDef } from "./apiEndpointTypes";

/** Rotas adicionais (auth estendido, CRM, relatórios, billing, treino, admin). */
export const EXTRA_API_CATALOG: ApiEndpointDef[] = [
  { method: "POST", path: "/api/auth/refresh", auth: false, category: "Auth", description: "Novo access token (body: refreshToken)." },
  { method: "POST", path: "/api/auth/logout", auth: false, category: "Auth", description: "Revoga refresh token opcional." },
  { method: "POST", path: "/api/auth/forgot-password", auth: false, category: "Auth", description: "Solicita reset (sempre 200; log dev com link)." },
  { method: "POST", path: "/api/auth/reset-password", auth: false, category: "Auth", description: "Redefine senha (token + newPassword)." },
  { method: "PATCH", path: "/api/me", auth: true, category: "Auth", description: "Atualização parcial nome / avatarUrl / preferences." },
  { method: "GET", path: "/api/me/preferences", auth: true, category: "Auth", description: "Lê JSON de preferências." },
  { method: "PUT", path: "/api/me/preferences", auth: true, category: "Auth", description: "Merge de preferências JSON." },
  { method: "PUT", path: "/api/me/password", auth: true, category: "Auth", description: "Altera senha (currentPassword, newPassword)." },
  { method: "GET", path: "/api/clients", auth: true, category: "CRM", description: "Lista clientes (payload JSON)." },
  { method: "POST", path: "/api/clients", auth: true, category: "CRM", description: "Cria cliente." },
  { method: "GET", path: "/api/clients/:id", auth: true, category: "CRM", description: "Detalhe cliente." },
  { method: "PATCH", path: "/api/clients/:id", auth: true, category: "CRM", description: "Merge parcial do payload." },
  { method: "DELETE", path: "/api/clients/:id", auth: true, category: "CRM", description: "Remove cliente." },
  { method: "GET", path: "/api/clients/:id/meetings", auth: true, category: "CRM", description: "Reuniões do usuário (filtro opcional q)." },
  { method: "PATCH", path: "/api/meetings/:id", auth: true, category: "Reuniões (CRUD)", description: "Atualiza reunião." },
  { method: "DELETE", path: "/api/meetings/:id", auth: true, category: "Reuniões (CRUD)", description: "Apaga reunião e relações." },
  { method: "POST", path: "/api/meetings/:id/duplicate", auth: true, category: "Reuniões (CRUD)", description: "Duplica reunião (sem clipes/insights)." },
  { method: "GET", path: "/api/teams/:id", auth: true, category: "Times", description: "Detalhe do time (owner)." },
  { method: "PATCH", path: "/api/teams/:id", auth: true, category: "Times", description: "Atualiza nome (owner)." },
  { method: "DELETE", path: "/api/teams/:id", auth: true, category: "Times", description: "Remove time e convites." },
  { method: "GET", path: "/api/teams/:id/invites", auth: true, category: "Times", description: "Convites pendentes do time (owner)." },
  { method: "DELETE", path: "/api/invites/:id", auth: true, category: "Times", description: "Cancela convite pendente (quem convidou)." },
  { method: "GET", path: "/api/reports/kpis", auth: true, category: "Relatórios", description: "KPIs agregados das reuniões." },
  { method: "GET", path: "/api/reports/meetings-by-day", auth: true, category: "Relatórios", description: "Contagem por dia." },
  { method: "GET", path: "/api/reports/history", auth: true, category: "Relatórios", description: "Histórico simplificado (limit)." },
  { method: "GET", path: "/api/reports/outcome-distribution", auth: true, category: "Relatórios", description: "Distribuição por resultado." },
  { method: "GET", path: "/api/reports/sentiment-over-time", auth: true, category: "Relatórios", description: "Sentimento por reunião (insights)." },
  { method: "GET", path: "/api/reports/talk-to-listen", auth: true, category: "Relatórios", description: "Placeholder por pipelineStage." },
  { method: "GET", path: "/api/billing/plan", auth: true, category: "Billing", description: "Plano e ciclo (UserBilling)." },
  { method: "GET", path: "/api/billing/usage", auth: true, category: "Billing", description: "Resumo uso tokens + shape empresa." },
  { method: "GET", path: "/api/billing/usage/entries", auth: true, category: "Billing", description: "Entradas de consumo JSON." },
  { method: "POST", path: "/api/billing/checkout", auth: true, category: "Billing", description: "Stub checkout (Stripe futuro)." },
  { method: "POST", path: "/api/billing/webhooks/stripe", auth: false, category: "Billing", description: "Stub webhook." },
  { method: "GET", path: "/api/training/product/progress", auth: true, category: "Treinamentos", description: "Lições concluídas." },
  { method: "POST", path: "/api/training/lessons/:lessonId/complete", auth: true, category: "Treinamentos", description: "Marca lição completa." },
  { method: "GET", path: "/api/training/dashboards/me", auth: true, category: "Treinamentos", description: "Métricas + progresso persistido." },
  { method: "POST", path: "/api/training/simulations/message", auth: true, category: "Treinamentos", description: "Alias do simulador (turno IA)." },
  { method: "DELETE", path: "/api/agents/:id", auth: true, category: "Agentes", description: "Remove agente e config." },
  { method: "POST", path: "/api/agents/:id/duplicate", auth: true, category: "Agentes", description: "Duplica agente + config." },
  { method: "GET", path: "/api/prompts/detail/:id", auth: true, category: "Prompts", description: "Prompt por id." },
  { method: "PATCH", path: "/api/prompts/:id", auth: true, category: "Prompts", description: "Atualização parcial (admin/supervisor)." },
  { method: "GET", path: "/api/admin/users", auth: true, category: "Admin", description: "Lista usuários (role admin)." },
  { method: "PATCH", path: "/api/admin/users/:id", auth: true, category: "Admin", description: "role / isActive (admin)." },
  { method: "GET", path: "/api/version", auth: false, category: "Sistema", description: "Versão da API." },
  { method: "GET", path: "/api/openapi.json", auth: false, category: "Sistema", description: "OpenAPI mínimo (stubs)." },
];
